### ISSUE TITLE
The link of "Privacy Policy" and "Terms of Use" link back to about us.

### ISSUE THREAD

**Issue by Garima2505** [gcivil-nyu-org/fall2019-cs-gy-6063-team-stellar#193]
## Expected Behavior

When clicking on the "Privacy Policy" and "Terms of Use" link, it should redirect to their respected pages and not to the "About Us" page.
 
## Current Behavior

When clicking on "Privacy Policy" and "Terms of Use", it redirects to the "About Us" page

**Comment by de846** [comment]
I have this issue too.

**Comment by YixinHu0321** [comment]
#185 duplicate
