### ISSUE TITLE
Invalid URL Redirection Issue

### ISSUE THREAD

**Issue by Garima2505** [gcivil-nyu-org/fall2019-cs-gy-6063-team-stellar#194]
## Expected Behavior

Redirection to 404 Not found the page
## Current Behavior

<img width="1440" alt="Screen Shot 2019-11-26 at 7 24 31 PM" src="https://user-images.githubusercontent.com/54910935/69683727-d9429100-1083-11ea-8573-dae517a65303.png">

When appending random characters to the URL it redirects to Debug page. 
## Ideas for Improvement

Catch the request to identify null requests handle them by redirecting to custom 404 Page 
## Steps to Reproduce

1. Add random characters to URL

**Comment by YixinHu0321** [comment]
#184 duplicate
