### ISSUE TITLE
Unable to recover password

### ISSUE THREAD

**Issue by Ayushi-0903** [gcivil-nyu-org/fall2019-cs-gy-6063-team-stellar#196]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I am unable to recover/change password

## Expected Behavior
I want to recover password if I forget password.

## Current Behavior
I am unable to recover password.

## Ideas for Improvement
Add functionality of forget password or change password

**Comment by YixinHu0321** [comment]
#183 duplicate
