### ISSUE TITLE
Sign Up form fails silently

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-stellar#197]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Since no account was created for me, I attempted to create my own account. The first time I submitted the form it sent me back to the login page with no indication that I was able to log in. Attempting to log in with my seemingly valid credentials failed.

## Expected Behavior
Form errors redirect to the signup page and display errors.

## Current Behavior
Form errors redirect to the index/login page.

## Ideas for Improvement
If there was an issue with signup fields, display form errors.

## Steps to Reproduce

1. fill in asdf for every field except email address and phone number
2. submit
3. get redirected to home page.

**Comment by utkarshp21** [comment]
@ab7289 - We tried reproducing the error but its seems to be working fine, can you please share screen recording. Sorry for the inconvenience, thanks :)
