### ISSUE TITLE
Selecting a preferred school doesn't limit choices on department

### ISSUE THREAD

**Issue by de846** [gcivil-nyu-org/fall2019-cs-gy-6063-team-stellar#199]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Choosing a preferred school should limit the choices that are available under preferred department to departments that are in that school.
## Current Behavior
You can pick a school, then pick some random department, and it changes your preferred school.

## Ideas for Improvement
Limit the choices available based on the current value of preferred school.

## Steps to Reproduce
1. Pick Tandon School of Engineering
2. Pick ABN: Adult Care
3. Watch the school change

I am trying to upload a video of it happening but cannot in Github. Please let me know what email I can send it to (its 77MB).

**Comment by YixinHu0321** [comment]
#181  duplicate
